
package john.com.drrs.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecondaryImplService", targetNamespace = "http://ws.drrs.com/", wsdlLocation = "http://localhost:9998/ws/secondary?wsdl")
public class SecondaryImplService
    extends Service
{

    private final static URL SECONDARYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECONDARYIMPLSERVICE_EXCEPTION;
    private final static QName SECONDARYIMPLSERVICE_QNAME = new QName("http://ws.drrs.com/", "SecondaryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9998/ws/secondary?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECONDARYIMPLSERVICE_WSDL_LOCATION = url;
        SECONDARYIMPLSERVICE_EXCEPTION = e;
    }

    public SecondaryImplService() {
        super(__getWsdlLocation(), SECONDARYIMPLSERVICE_QNAME);
    }

    public SecondaryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECONDARYIMPLSERVICE_QNAME, features);
    }

    public SecondaryImplService(URL wsdlLocation) {
        super(wsdlLocation, SECONDARYIMPLSERVICE_QNAME);
    }

    public SecondaryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECONDARYIMPLSERVICE_QNAME, features);
    }

    public SecondaryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecondaryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Secondary
     */
    @WebEndpoint(name = "SecondaryImplPort")
    public Secondary getSecondaryImplPort() {
        return super.getPort(new QName("http://ws.drrs.com/", "SecondaryImplPort"), Secondary.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Secondary
     */
    @WebEndpoint(name = "SecondaryImplPort")
    public Secondary getSecondaryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.drrs.com/", "SecondaryImplPort"), Secondary.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECONDARYIMPLSERVICE_EXCEPTION!= null) {
            throw SECONDARYIMPLSERVICE_EXCEPTION;
        }
        return SECONDARYIMPLSERVICE_WSDL_LOCATION;
    }

}
