
package john.com.drrs.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Secondary", targetNamespace = "http://ws.drrs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Secondary {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableTimeSlots", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.GetAvailableTimeSlots")
    @ResponseWrapper(localName = "getAvailableTimeSlotsResponse", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.GetAvailableTimeSlotsResponse")
    @Action(input = "http://ws.drrs.com/Secondary/getAvailableTimeSlotsRequest", output = "http://ws.drrs.com/Secondary/getAvailableTimeSlotsResponse")
    public int getAvailableTimeSlots(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeReservation", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.ChangeReservation")
    @ResponseWrapper(localName = "changeReservationResponse", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.ChangeReservationResponse")
    @Action(input = "http://ws.drrs.com/Secondary/changeReservationRequest", output = "http://ws.drrs.com/Secondary/changeReservationResponse")
    public boolean changeReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelBooking", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.CancelBooking")
    @ResponseWrapper(localName = "cancelBookingResponse", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.CancelBookingResponse")
    @Action(input = "http://ws.drrs.com/Secondary/cancelBookingRequest", output = "http://ws.drrs.com/Secondary/cancelBookingResponse")
    public boolean cancelBooking(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "secondaryTest", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.SecondaryTest")
    @ResponseWrapper(localName = "secondaryTestResponse", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.SecondaryTestResponse")
    @Action(input = "http://ws.drrs.com/Secondary/secondaryTestRequest", output = "http://ws.drrs.com/Secondary/secondaryTestResponse")
    public String secondaryTest();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createRoom", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.CreateRoom")
    @ResponseWrapper(localName = "createRoomResponse", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.CreateRoomResponse")
    @Action(input = "http://ws.drrs.com/Secondary/createRoomRequest", output = "http://ws.drrs.com/Secondary/createRoomResponse")
    public boolean createRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteRoom", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.DeleteRoom")
    @ResponseWrapper(localName = "deleteRoomResponse", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.DeleteRoomResponse")
    @Action(input = "http://ws.drrs.com/Secondary/deleteRoomRequest", output = "http://ws.drrs.com/Secondary/deleteRoomResponse")
    public boolean deleteRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookRoom", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.BookRoom")
    @ResponseWrapper(localName = "bookRoomResponse", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.BookRoomResponse")
    @Action(input = "http://ws.drrs.com/Secondary/bookRoomRequest", output = "http://ws.drrs.com/Secondary/bookRoomResponse")
    public String bookRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooking", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.GetBooking")
    @ResponseWrapper(localName = "getBookingResponse", targetNamespace = "http://ws.drrs.com/", className = "com.drrs.ws.GetBookingResponse")
    @Action(input = "http://ws.drrs.com/Secondary/getBookingRequest", output = "http://ws.drrs.com/Secondary/getBookingResponse")
    public String getBooking(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
