
package com.drrs.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrimaryImplService", targetNamespace = "http://ws.drrs.com/", wsdlLocation = "http://localhost:9999/ws/primary?wsdl")
public class PrimaryImplService
    extends Service
{

    private final static URL PRIMARYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRIMARYIMPLSERVICE_EXCEPTION;
    private final static QName PRIMARYIMPLSERVICE_QNAME = new QName("http://ws.drrs.com/", "PrimaryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/primary?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRIMARYIMPLSERVICE_WSDL_LOCATION = url;
        PRIMARYIMPLSERVICE_EXCEPTION = e;
    }

    public PrimaryImplService() {
        super(__getWsdlLocation(), PRIMARYIMPLSERVICE_QNAME);
    }

    public PrimaryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRIMARYIMPLSERVICE_QNAME, features);
    }

    public PrimaryImplService(URL wsdlLocation) {
        super(wsdlLocation, PRIMARYIMPLSERVICE_QNAME);
    }

    public PrimaryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRIMARYIMPLSERVICE_QNAME, features);
    }

    public PrimaryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrimaryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Primary
     */
    @WebEndpoint(name = "PrimaryImplPort")
    public Primary getPrimaryImplPort() {
        return super.getPort(new QName("http://ws.drrs.com/", "PrimaryImplPort"), Primary.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Primary
     */
    @WebEndpoint(name = "PrimaryImplPort")
    public Primary getPrimaryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.drrs.com/", "PrimaryImplPort"), Primary.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRIMARYIMPLSERVICE_EXCEPTION!= null) {
            throw PRIMARYIMPLSERVICE_EXCEPTION;
        }
        return PRIMARYIMPLSERVICE_WSDL_LOCATION;
    }

}
